# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/physical_properties_widget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PhysicalPropertiesWidget(object):
    def setupUi(self, PhysicalPropertiesWidget):
        PhysicalPropertiesWidget.setObjectName("PhysicalPropertiesWidget")
        PhysicalPropertiesWidget.resize(483, 337)
        PhysicalPropertiesWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(PhysicalPropertiesWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblCartFriction = QtWidgets.QLabel(PhysicalPropertiesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCartFriction.sizePolicy().hasHeightForWidth())
        self.lblCartFriction.setSizePolicy(sizePolicy)
        self.lblCartFriction.setObjectName("lblCartFriction")
        self.gridLayout.addWidget(self.lblCartFriction, 5, 0, 1, 1)
        self.spnCartFriction = QtWidgets.QDoubleSpinBox(PhysicalPropertiesWidget)
        self.spnCartFriction.setDecimals(6)
        self.spnCartFriction.setSingleStep(0.05)
        self.spnCartFriction.setObjectName("spnCartFriction")
        self.gridLayout.addWidget(self.spnCartFriction, 5, 1, 1, 1)
        self.spnPoleMass = QtWidgets.QDoubleSpinBox(PhysicalPropertiesWidget)
        self.spnPoleMass.setSingleStep(0.25)
        self.spnPoleMass.setObjectName("spnPoleMass")
        self.gridLayout.addWidget(self.spnPoleMass, 3, 1, 1, 1)
        self.lblPoleLength = QtWidgets.QLabel(PhysicalPropertiesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPoleLength.sizePolicy().hasHeightForWidth())
        self.lblPoleLength.setSizePolicy(sizePolicy)
        self.lblPoleLength.setObjectName("lblPoleLength")
        self.gridLayout.addWidget(self.lblPoleLength, 4, 0, 1, 1)
        self.spnRightBound = QtWidgets.QDoubleSpinBox(PhysicalPropertiesWidget)
        self.spnRightBound.setMinimum(-100.0)
        self.spnRightBound.setMaximum(100.0)
        self.spnRightBound.setSingleStep(0.1)
        self.spnRightBound.setObjectName("spnRightBound")
        self.gridLayout.addWidget(self.spnRightBound, 8, 1, 1, 1)
        self.lblAngleTolerance = QtWidgets.QLabel(PhysicalPropertiesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAngleTolerance.sizePolicy().hasHeightForWidth())
        self.lblAngleTolerance.setSizePolicy(sizePolicy)
        self.lblAngleTolerance.setObjectName("lblAngleTolerance")
        self.gridLayout.addWidget(self.lblAngleTolerance, 9, 0, 1, 1)
        self.lblModel = QtWidgets.QLabel(PhysicalPropertiesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblModel.sizePolicy().hasHeightForWidth())
        self.lblModel.setSizePolicy(sizePolicy)
        self.lblModel.setObjectName("lblModel")
        self.gridLayout.addWidget(self.lblModel, 0, 0, 1, 1)
        self.cboModel = QtWidgets.QComboBox(PhysicalPropertiesWidget)
        self.cboModel.setObjectName("cboModel")
        self.cboModel.addItem("")
        self.cboModel.addItem("")
        self.cboModel.addItem("")
        self.gridLayout.addWidget(self.cboModel, 0, 1, 1, 1)
        self.lblCartMass = QtWidgets.QLabel(PhysicalPropertiesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCartMass.sizePolicy().hasHeightForWidth())
        self.lblCartMass.setSizePolicy(sizePolicy)
        self.lblCartMass.setObjectName("lblCartMass")
        self.gridLayout.addWidget(self.lblCartMass, 2, 0, 1, 1)
        self.spnPoleFriction = QtWidgets.QDoubleSpinBox(PhysicalPropertiesWidget)
        self.spnPoleFriction.setDecimals(6)
        self.spnPoleFriction.setSingleStep(0.05)
        self.spnPoleFriction.setObjectName("spnPoleFriction")
        self.gridLayout.addWidget(self.spnPoleFriction, 6, 1, 1, 1)
        self.lblLeftBound = QtWidgets.QLabel(PhysicalPropertiesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLeftBound.sizePolicy().hasHeightForWidth())
        self.lblLeftBound.setSizePolicy(sizePolicy)
        self.lblLeftBound.setObjectName("lblLeftBound")
        self.gridLayout.addWidget(self.lblLeftBound, 7, 0, 1, 1)
        self.spnPoleLength = QtWidgets.QDoubleSpinBox(PhysicalPropertiesWidget)
        self.spnPoleLength.setMinimum(0.1)
        self.spnPoleLength.setSingleStep(0.1)
        self.spnPoleLength.setObjectName("spnPoleLength")
        self.gridLayout.addWidget(self.spnPoleLength, 4, 1, 1, 1)
        self.spnAngleTolerance = QtWidgets.QDoubleSpinBox(PhysicalPropertiesWidget)
        self.spnAngleTolerance.setMaximum(180.0)
        self.spnAngleTolerance.setObjectName("spnAngleTolerance")
        self.gridLayout.addWidget(self.spnAngleTolerance, 9, 1, 1, 1)
        self.lblPoleMass = QtWidgets.QLabel(PhysicalPropertiesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPoleMass.sizePolicy().hasHeightForWidth())
        self.lblPoleMass.setSizePolicy(sizePolicy)
        self.lblPoleMass.setObjectName("lblPoleMass")
        self.gridLayout.addWidget(self.lblPoleMass, 3, 0, 1, 1)
        self.lblGravity = QtWidgets.QLabel(PhysicalPropertiesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGravity.sizePolicy().hasHeightForWidth())
        self.lblGravity.setSizePolicy(sizePolicy)
        self.lblGravity.setObjectName("lblGravity")
        self.gridLayout.addWidget(self.lblGravity, 1, 0, 1, 1)
        self.spnGravity = QtWidgets.QDoubleSpinBox(PhysicalPropertiesWidget)
        self.spnGravity.setObjectName("spnGravity")
        self.gridLayout.addWidget(self.spnGravity, 1, 1, 1, 1)
        self.btnShowAngleTolerance = QtWidgets.QToolButton(PhysicalPropertiesWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/pen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnShowAngleTolerance.setIcon(icon)
        self.btnShowAngleTolerance.setCheckable(True)
        self.btnShowAngleTolerance.setAutoRaise(True)
        self.btnShowAngleTolerance.setObjectName("btnShowAngleTolerance")
        self.gridLayout.addWidget(self.btnShowAngleTolerance, 9, 2, 1, 1)
        self.lblPoleFriction = QtWidgets.QLabel(PhysicalPropertiesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPoleFriction.sizePolicy().hasHeightForWidth())
        self.lblPoleFriction.setSizePolicy(sizePolicy)
        self.lblPoleFriction.setObjectName("lblPoleFriction")
        self.gridLayout.addWidget(self.lblPoleFriction, 6, 0, 1, 1)
        self.spnCartMass = QtWidgets.QDoubleSpinBox(PhysicalPropertiesWidget)
        self.spnCartMass.setSingleStep(0.25)
        self.spnCartMass.setObjectName("spnCartMass")
        self.gridLayout.addWidget(self.spnCartMass, 2, 1, 1, 1)
        self.spnLeftBound = QtWidgets.QDoubleSpinBox(PhysicalPropertiesWidget)
        self.spnLeftBound.setMinimum(-100.0)
        self.spnLeftBound.setMaximum(100.0)
        self.spnLeftBound.setSingleStep(0.1)
        self.spnLeftBound.setObjectName("spnLeftBound")
        self.gridLayout.addWidget(self.spnLeftBound, 7, 1, 1, 1)
        self.lblRightBound = QtWidgets.QLabel(PhysicalPropertiesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRightBound.sizePolicy().hasHeightForWidth())
        self.lblRightBound.setSizePolicy(sizePolicy)
        self.lblRightBound.setObjectName("lblRightBound")
        self.gridLayout.addWidget(self.lblRightBound, 8, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 1, 1, 1)
        self.lblCartFriction.setBuddy(self.spnCartFriction)
        self.lblPoleLength.setBuddy(self.spnPoleLength)
        self.lblAngleTolerance.setBuddy(self.spnAngleTolerance)
        self.lblModel.setBuddy(self.cboModel)
        self.lblCartMass.setBuddy(self.spnCartMass)
        self.lblLeftBound.setBuddy(self.spnLeftBound)
        self.lblPoleMass.setBuddy(self.spnPoleMass)
        self.lblGravity.setBuddy(self.spnGravity)
        self.lblPoleFriction.setBuddy(self.spnPoleFriction)
        self.lblRightBound.setBuddy(self.spnRightBound)

        self.retranslateUi(PhysicalPropertiesWidget)
        QtCore.QMetaObject.connectSlotsByName(PhysicalPropertiesWidget)
        PhysicalPropertiesWidget.setTabOrder(self.cboModel, self.spnGravity)
        PhysicalPropertiesWidget.setTabOrder(self.spnGravity, self.spnCartMass)
        PhysicalPropertiesWidget.setTabOrder(self.spnCartMass, self.spnPoleMass)
        PhysicalPropertiesWidget.setTabOrder(self.spnPoleMass, self.spnPoleLength)
        PhysicalPropertiesWidget.setTabOrder(self.spnPoleLength, self.spnCartFriction)
        PhysicalPropertiesWidget.setTabOrder(self.spnCartFriction, self.spnPoleFriction)
        PhysicalPropertiesWidget.setTabOrder(self.spnPoleFriction, self.spnLeftBound)
        PhysicalPropertiesWidget.setTabOrder(self.spnLeftBound, self.spnRightBound)
        PhysicalPropertiesWidget.setTabOrder(self.spnRightBound, self.spnAngleTolerance)
        PhysicalPropertiesWidget.setTabOrder(self.spnAngleTolerance, self.btnShowAngleTolerance)

    def retranslateUi(self, PhysicalPropertiesWidget):
        _translate = QtCore.QCoreApplication.translate
        PhysicalPropertiesWidget.setWindowTitle(_translate("PhysicalPropertiesWidget", "Physics properties"))
        self.lblCartFriction.setText(_translate("PhysicalPropertiesWidget", "Cart friction:"))
        self.lblPoleLength.setText(_translate("PhysicalPropertiesWidget", "Pole length (m):"))
        self.lblAngleTolerance.setText(_translate("PhysicalPropertiesWidget", "Angle tolerance (deg):"))
        self.lblModel.setText(_translate("PhysicalPropertiesWidget", "Model:"))
        self.cboModel.setItemText(0, _translate("PhysicalPropertiesWidget", "Razvan with friction"))
        self.cboModel.setItemText(1, _translate("PhysicalPropertiesWidget", "Razvan without friction"))
        self.cboModel.setItemText(2, _translate("PhysicalPropertiesWidget", "Barto with friction"))
        self.lblCartMass.setText(_translate("PhysicalPropertiesWidget", "Cart mass (kg):"))
        self.lblLeftBound.setText(_translate("PhysicalPropertiesWidget", "Left bound (m):"))
        self.lblPoleMass.setText(_translate("PhysicalPropertiesWidget", "Pole mass (kg):"))
        self.lblGravity.setText(_translate("PhysicalPropertiesWidget", "Gravity (m/s^2):"))
        self.btnShowAngleTolerance.setToolTip(_translate("PhysicalPropertiesWidget", "Show angle tolerance"))
        self.btnShowAngleTolerance.setText(_translate("PhysicalPropertiesWidget", "..."))
        self.lblPoleFriction.setText(_translate("PhysicalPropertiesWidget", "Pole friction:"))
        self.lblRightBound.setText(_translate("PhysicalPropertiesWidget", "Right bound(m):"))

import resources_rc
